/*
 * Copyright 2024 InfAI (CC SES)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package controller

import (
	"context"
	"net/http"
	"slices"
	"strings"

	"github.com/SENERGY-Platform/device-repository/v2/lib/idmodifier"
	"github.com/SENERGY-Platform/device-repository/v2/lib/model"
	"github.com/SENERGY-Platform/models/go/models"
)

func (this *Controller) EnsureGeneratedDeviceGroup(oldDevice models.Device, device models.Device) (err error) {
	if this.config.SkipDeviceGroupGenerationFromDevice {
		return nil
	}
	virtualDgId := this.DeviceIdToGeneratedDeviceGroupId(device.Id)
	ctx, _ := getTimeoutContext()
	old, exists, err := this.db.GetDeviceGroup(ctx, virtualDgId)
	if err != nil {
		return err
	}
	if exists {
		if oldDevice.Id == "" {
			//we don't know what the old name has been --> we don't know if the user has changed the device-group name manually
			return nil
		}
		oldDeviceName := getDeviceDisplayName(oldDevice)
		if old.Name != oldDeviceName && old.Name != oldDeviceName+"_group" {
			//the user has changed the device-group name manually -> we don't overwrite user changes
			return nil
		}
		if len(old.DeviceIds) != 1 {
			//we don't change the name of edited device-groups
			return nil
		}
		if old.DeviceIds[0] != device.Id {
			//we don't change the name of edited device-groups
			return nil
		}
	}
	dg := models.DeviceGroup{
		Id:                    virtualDgId,
		Name:                  getDeviceDisplayName(device),
		DeviceIds:             []string{device.Id},
		AutoGeneratedByDevice: device.Id,
		Attributes: []models.Attribute{{
			Key:    "platform/generated",
			Value:  "true",
			Origin: "device-repository",
		}},
	}
	dg.Criteria, err, _ = this.getDeviceGroupCriteriaOfDevice(device)
	if err != nil {
		return err
	}
	slices.SortFunc(dg.Criteria, func(a, b models.DeviceGroupFilterCriteria) int {
		return strings.Compare(a.Short(), b.Short())
	})
	dg.SetShortCriteria()
	return this.setDeviceGroup(dg, device.OwnerId)
}

func getDeviceDisplayName(device models.Device) string {
	displayName := device.Name
	for _, attr := range device.Attributes {
		if attr.Key == "shared/nickname" && attr.Value != "" {
			displayName = attr.Value
		}
	}
	return displayName
}

func (this *Controller) RemoveGeneratedDeviceGroup(deviceid string, owner string) error {
	virtualDgId := this.DeviceIdToGeneratedDeviceGroupId(deviceid)
	ctx, _ := getTimeoutContext()
	dg, exists, err := this.db.GetDeviceGroup(ctx, virtualDgId)
	if err != nil {
		return err
	}
	if !exists {
		return nil
	}
	dg.DeviceIds = slices.DeleteFunc(dg.DeviceIds, func(s string) bool {
		return s == deviceid
	})
	if len(dg.DeviceIds) > 0 {
		dg.AutoGeneratedByDevice = ""
		return this.setDeviceGroup(dg, owner)
	} else {
		return this.deleteDeviceGroup(virtualDgId)
	}
}

func (this *Controller) DeviceIdToGeneratedDeviceGroupId(deviceId string) string {
	return model.DeviceIdToGeneratedDeviceGroupId(deviceId)
}

// GetDeviceGroupCriteria is the criteria list of a device-group holding the given devices: the
// intersection of the criteria of its devices by Short(). A function reaches the group only if
// every device answers it, and an aspect only if every device carries it or a descendant of it.
func (this *Controller) GetDeviceGroupCriteria(deviceIds []string) (result []models.DeviceGroupFilterCriteria, err error, code int) {
	result = []models.DeviceGroupFilterCriteria{}
	if len(deviceIds) == 0 {
		return result, nil, http.StatusOK
	}

	//a device-group may hold modified device ids; the stored device sits under the pure id and
	//the modifier decides which of its services the group member actually answers
	pureIds := []string{}
	pureIdToRawIds := map[string][]string{}
	for _, id := range deviceIds {
		pureId, _ := idmodifier.SplitModifier(id)
		if !slices.Contains(pureIds, pureId) {
			pureIds = append(pureIds, pureId)
		}
		pureIdToRawIds[pureId] = append(pureIdToRawIds[pureId], id)
	}

	devices, _, err := this.db.ListDevices(context.Background(), model.DeviceListOptions{Ids: pureIds}, false)
	if err != nil {
		return result, err, http.StatusInternalServerError
	}

	currentSet := map[string]models.DeviceGroupFilterCriteria{}
	first := true
	for _, device := range devices {
		for _, rawId := range pureIdToRawIds[device.Id] {
			member := device.Device
			_, modifier := idmodifier.SplitModifier(rawId)
			if len(modifier) > 0 {
				member, err, code = this.modifyDevice(member, modifier)
				if err != nil {
					return result, err, code
				}
			}
			deviceCriterias, err, code := this.getDeviceGroupCriteriaOfDevice(member)
			if err != nil {
				return result, err, code
			}
			nextSet := map[string]models.DeviceGroupFilterCriteria{}
			for _, criteria := range deviceCriterias {
				criteriaShort := criteria.Short()
				_, usedInCurrent := currentSet[criteriaShort]
				if first || usedInCurrent {
					nextSet[criteriaShort] = criteria
				}
			}
			currentSet = nextSet
			first = false
		}
	}
	for _, element := range currentSet {
		result = append(result, element)
	}
	return result, nil, http.StatusOK
}

func (this *Controller) getDeviceGroupCriteriaOfDevice(device models.Device) (result []models.DeviceGroupFilterCriteria, err error, code int) {
	ctx, _ := getTimeoutContext()
	pureDtId, modifier := idmodifier.SplitModifier(device.DeviceTypeId)
	deviceType, exists, err := this.db.GetDeviceType(ctx, pureDtId)
	if err != nil {
		return result, err, http.StatusInternalServerError
	}
	if !exists {
		//a device may outlive its device-type: the startup migration walks whatever is stored
		//and must not abort over one dangling reference. Such a device answers nothing, which
		//empties the criteria of every group holding it.
		this.config.GetLogger().Warn("no criteria for device: device-type not found", "device-id", device.Id, "device-type-id", device.DeviceTypeId)
		return result, nil, http.StatusOK
	}
	//read straight from the database: device-types written before the migration carry only
	//the deprecated ContentVariable.AspectId, and the criteria below evaluate AspectIds
	SetContentVariableAspectIdsOnWrite(&deviceType)
	//a modified device answers only the services its modifier keeps, so its criteria are the
	//criteria of the modified device-type, not of the stored one
	if len(modifier) > 0 {
		deviceType, err, code = this.modifyDeviceType(deviceType, modifier)
		if err != nil {
			return result, err, code
		}
	}
	resultSet := map[string]models.DeviceGroupFilterCriteria{}
	for _, service := range deviceType.Services {
		interactions := []models.Interaction{service.Interaction}
		if service.Interaction == models.EVENT_AND_REQUEST {
			interactions = []models.Interaction{models.EVENT, models.REQUEST}
		}
		work := []models.ContentVariable{}
		for _, content := range service.Inputs {
			work = append(work, content.ContentVariable)
		}
		for _, content := range service.Outputs {
			work = append(work, content.ContentVariable)
		}
		for i := 0; i < len(work); i++ {
			current := work[i]
			if current.FunctionId != "" {
				for _, interaction := range interactions {
					if isMeasuringFunctionId(current.FunctionId) {
						err = this.addMeasuringDeviceGroupCriteria(ctx, current.FunctionId, current.AspectIds, interaction, resultSet)
						if err != nil {
							return result, err, http.StatusInternalServerError
						}
					} else {
						criteria := models.DeviceGroupFilterCriteria{
							FunctionId:    current.FunctionId,
							DeviceClassId: deviceType.DeviceClassId,
							Interaction:   interaction,
						}
						resultSet[criteria.Short()] = criteria
					}
				}
			}
			if len(current.SubContentVariables) > 0 {
				work = append(work, current.SubContentVariables...)
			}
		}
	}
	for _, element := range resultSet {
		result = append(result, element)
	}
	return result, nil, http.StatusOK
}

// addMeasuringDeviceGroupCriteria adds the criteria of one content variable of a measuring
// function to the criteria set of a device.
//
// An aspect criteria covers the subtree of its node, so a variable is found by a query naming
// an ancestor of one of its aspects: a variable carrying [q r] is found by a query over [p r]
// when q descends from p. Every aspect of the list is therefore replaced by itself or by one
// of its ancestors, and each of those combinations becomes a criteria - that is what records
// that one variable carries all the aspects of the combination. For a single aspect the
// product is the aspect and its ancestors, which is what a criteria over one aspect has
// always been.
//
// The single aspects are added next to those combinations, because they carry the
// intersection: GetDeviceGroupCriteria intersects the criteria of the devices by Short(), so
// a group of a device with [a b] and one with [a] keeps a only if a stands alone.
func (this *Controller) addMeasuringDeviceGroupCriteria(ctx context.Context, functionId string, aspectIds []string, interaction models.Interaction, resultSet map[string]models.DeviceGroupFilterCriteria) (err error) {
	add := func(aspectIds []string) {
		criteria := measuringDeviceGroupCriteria(functionId, aspectIds, interaction)
		resultSet[criteria.Short()] = criteria
	}
	aspectOptions := make([][]string, 0, len(aspectIds))
	for _, aspectId := range aspectIds {
		aspectNode, _, err := this.db.GetAspectNode(ctx, aspectId)
		if err != nil {
			return err
		}
		options := append([]string{aspectId}, aspectNode.AncestorIds...)
		aspectOptions = append(aspectOptions, options)
		for _, option := range options {
			add([]string{option})
		}
	}
	for _, combination := range aspectIdCombinations(aspectOptions) {
		add(combination)
	}
	return nil
}

// aspectIdCombinations builds the cartesian product of the aspect options of a content
// variable, one option list per aspect of the variable. Without any aspect the product is the
// single empty combination, which is the criteria of a measuring variable carrying no aspect.
// The result grows with the number of aspects of one variable to the power of their depth in
// the hierarchy, which is small for the one or two aspects a variable realistically carries.
func aspectIdCombinations(aspectOptions [][]string) (result [][]string) {
	result = [][]string{{}}
	for _, options := range aspectOptions {
		next := make([][]string, 0, len(result)*len(options))
		for _, combination := range result {
			for _, aspectId := range options {
				next = append(next, append(slices.Clone(combination), aspectId))
			}
		}
		result = next
	}
	return result
}

// measuringDeviceGroupCriteria builds a criteria over an aspect list. The list is sorted, so
// that the same set of aspects always renders the same Short(). The deprecated AspectId can
// only carry one aspect and gets the alphabetically first, like everywhere else.
func measuringDeviceGroupCriteria(functionId string, aspectIds []string, interaction models.Interaction) models.DeviceGroupFilterCriteria {
	criteria := models.DeviceGroupFilterCriteria{
		FunctionId:  functionId,
		Interaction: interaction,
	}
	if len(aspectIds) > 0 {
		criteria.AspectIds = slices.Compact(slices.Sorted(slices.Values(aspectIds)))
		criteria.AspectId = criteria.AspectIds[0]
	}
	return criteria
}

func isMeasuringFunctionId(id string) bool {
	if strings.HasPrefix(id, model.MEASURING_FUNCTION_PREFIX) {
		return true
	}
	return false
}
