/*
 * Copyright 2024 InfAI (CC SES)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package controller

import (
	"context"
	"github.com/SENERGY-Platform/device-repository/lib/model"
	"github.com/SENERGY-Platform/models/go/models"
	"net/http"
	"slices"
	"strings"
)

func (this *Controller) EnsureGeneratedDeviceGroup(oldDevice models.Device, device models.Device) (err error) {
	if this.config.SkipDeviceGroupGenerationFromDevice {
		return nil
	}
	virtualDgId := this.DeviceIdToGeneratedDeviceGroupId(device.Id)
	ctx, _ := getTimeoutContext()
	old, exists, err := this.db.GetDeviceGroup(ctx, virtualDgId)
	if err != nil {
		return err
	}
	if exists {
		if oldDevice.Id == "" {
			//we don't know what the old name has been --> we don't know if the user has changed the device-group name manually
			return nil
		}
		oldDeviceName := getDeviceDisplayName(oldDevice)
		if old.Name != oldDeviceName && old.Name != oldDeviceName+"_group" {
			//the user has changed the device-group name manually -> we don't overwrite user changes
			return nil
		}
		if len(old.DeviceIds) != 1 {
			//we don't change the name of edited device-groups
			return nil
		}
		if old.DeviceIds[0] != device.Id {
			//we don't change the name of edited device-groups
			return nil
		}
	}
	dg := models.DeviceGroup{
		Id:                    virtualDgId,
		Name:                  getDeviceDisplayName(device),
		DeviceIds:             []string{device.Id},
		AutoGeneratedByDevice: device.Id,
		Attributes: []models.Attribute{{
			Key:    "platform/generated",
			Value:  "true",
			Origin: "device-repository",
		}},
	}
	dg.Criteria, err, _ = this.getDeviceGroupCriteriaOfDevice(device)
	if err != nil {
		return err
	}
	slices.SortFunc(dg.Criteria, func(a, b models.DeviceGroupFilterCriteria) int {
		return strings.Compare(a.Short(), b.Short())
	})
	dg.SetShortCriteria()
	return this.setDeviceGroup(dg, device.OwnerId)
}

func getDeviceDisplayName(device models.Device) string {
	displayName := device.Name
	for _, attr := range device.Attributes {
		if attr.Key == "shared/nickname" && attr.Value != "" {
			displayName = attr.Value
		}
	}
	return displayName
}

func (this *Controller) RemoveGeneratedDeviceGroup(deviceid string, owner string) error {
	virtualDgId := this.DeviceIdToGeneratedDeviceGroupId(deviceid)
	ctx, _ := getTimeoutContext()
	dg, exists, err := this.db.GetDeviceGroup(ctx, virtualDgId)
	if err != nil {
		return err
	}
	if !exists {
		return nil
	}
	dg.DeviceIds = slices.DeleteFunc(dg.DeviceIds, func(s string) bool {
		return s == deviceid
	})
	if len(dg.DeviceIds) > 0 {
		dg.AutoGeneratedByDevice = ""
		return this.setDeviceGroup(dg, owner)
	} else {
		return this.deleteDeviceGroup(virtualDgId)
	}
}

func (this *Controller) DeviceIdToGeneratedDeviceGroupId(deviceId string) string {
	return model.DeviceIdToGeneratedDeviceGroupId(deviceId)
}

func (this *Controller) GetDeviceGroupCriteria(deviceIds []string) (result []models.DeviceGroupFilterCriteria, err error, code int) {
	devices, _, err := this.db.ListDevices(context.Background(), model.DeviceListOptions{Ids: deviceIds}, false)
	currentSet := map[string]models.DeviceGroupFilterCriteria{}
	for i, device := range devices {
		deviceCriterias, err, code := this.getDeviceGroupCriteriaOfDevice(device.Device)
		if err != nil {
			return result, err, code
		}
		nextSet := map[string]models.DeviceGroupFilterCriteria{}
		for _, criteria := range deviceCriterias {
			criteriaShort := criteria.Short()
			_, usedInCurrent := currentSet[criteriaShort]
			if i == 0 || usedInCurrent {
				nextSet[criteriaShort] = criteria
			}
		}
		currentSet = nextSet
	}
	result = []models.DeviceGroupFilterCriteria{}
	for _, element := range currentSet {
		result = append(result, element)
	}
	return result, nil, http.StatusOK
}

func (this *Controller) getDeviceGroupCriteriaOfDevice(device models.Device) (result []models.DeviceGroupFilterCriteria, err error, code int) {
	ctx, _ := getTimeoutContext()
	deviceType, _, err := this.db.GetDeviceType(ctx, device.DeviceTypeId)
	if err != nil {
		return result, err, http.StatusInternalServerError
	}
	//read straight from the database: device-types written before the migration carry only
	//the deprecated ContentVariable.AspectId, and the criteria below evaluate AspectIds
	SetContentVariableAspectIdsOnWrite(&deviceType)
	resultSet := map[string]models.DeviceGroupFilterCriteria{}
	for _, service := range deviceType.Services {
		interactions := []models.Interaction{service.Interaction}
		if service.Interaction == models.EVENT_AND_REQUEST {
			interactions = []models.Interaction{models.EVENT, models.REQUEST}
		}
		work := []models.ContentVariable{}
		for _, content := range service.Inputs {
			work = append(work, content.ContentVariable)
		}
		for _, content := range service.Outputs {
			work = append(work, content.ContentVariable)
		}
		for i := 0; i < len(work); i++ {
			current := work[i]
			if current.FunctionId != "" {
				for _, interaction := range interactions {
					if isMeasuringFunctionId(current.FunctionId) {
						//the whole aspect list of the content variable, which is the only
						//criteria that records that one variable carries all of them
						criteria := measuringDeviceGroupCriteria(current.FunctionId, current.AspectIds, interaction)
						resultSet[criteria.Short()] = criteria

						//and one criteria per aspect next to it. GetDeviceGroupCriteria
						//intersects the criteria of the devices by Short(), so a group of a
						//device with [a b] and one with [a] keeps a only if a stands alone.
						for _, aspectId := range current.AspectIds {
							criteria := measuringDeviceGroupCriteria(current.FunctionId, []string{aspectId}, interaction)
							resultSet[criteria.Short()] = criteria
							aspectNode, _, err := this.db.GetAspectNode(ctx, aspectId)
							if err != nil {
								return result, err, http.StatusInternalServerError
							}
							for _, aspect := range aspectNode.AncestorIds {
								criteria := measuringDeviceGroupCriteria(current.FunctionId, []string{aspect}, interaction)
								resultSet[criteria.Short()] = criteria
							}
						}
					} else {
						criteria := models.DeviceGroupFilterCriteria{
							FunctionId:    current.FunctionId,
							DeviceClassId: deviceType.DeviceClassId,
							Interaction:   interaction,
						}
						resultSet[criteria.Short()] = criteria
					}
				}
			}
			if len(current.SubContentVariables) > 0 {
				work = append(work, current.SubContentVariables...)
			}
		}
	}
	for _, element := range resultSet {
		result = append(result, element)
	}
	return result, nil, http.StatusOK
}

// measuringDeviceGroupCriteria builds a criteria over an aspect list. The list is sorted, so
// that the same set of aspects always renders the same Short(). The deprecated AspectId can
// only carry one aspect and gets the alphabetically first, like everywhere else.
func measuringDeviceGroupCriteria(functionId string, aspectIds []string, interaction models.Interaction) models.DeviceGroupFilterCriteria {
	criteria := models.DeviceGroupFilterCriteria{
		FunctionId:  functionId,
		Interaction: interaction,
	}
	if len(aspectIds) > 0 {
		criteria.AspectIds = slices.Compact(slices.Sorted(slices.Values(aspectIds)))
		criteria.AspectId = criteria.AspectIds[0]
	}
	return criteria
}

func isMeasuringFunctionId(id string) bool {
	if strings.HasPrefix(id, model.MEASURING_FUNCTION_PREFIX) {
		return true
	}
	return false
}
