/*
 * Copyright 2019 InfAI (CC SES)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package mongo

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/SENERGY-Platform/device-repository/lib/model"
	"github.com/SENERGY-Platform/models/go/models"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

var DeviceGroupBson = getBsonFieldObject[models.DeviceGroup]()

var deviceGroupCriteriaShortKey string

func init() {
	CreateCollections = append(CreateCollections, func(db *Mongo) error {
		var err error
		deviceGroupCriteriaShortKey, err = getBsonFieldName(models.DeviceGroup{}, "CriteriaShort")
		if err != nil {
			return err
		}
		collection := db.client.Database(db.config.MongoTable).Collection(db.config.MongoDeviceGroupCollection)
		err = db.ensureIndex(collection, "deviceGroupidindex", DeviceGroupBson.Id, true, true)
		if err != nil {
			return err
		}
		return nil
	})
}

func (this *Mongo) deviceGroupCollection() *mongo.Collection {
	return this.client.Database(this.config.MongoTable).Collection(this.config.MongoDeviceGroupCollection)
}

func (this *Mongo) GetDeviceGroup(ctx context.Context, id string) (deviceGroup models.DeviceGroup, exists bool, err error) {
	result := this.deviceGroupCollection().FindOne(ctx, bson.M{DeviceGroupBson.Id: id, NotDeletedFilterKey: NotDeletedFilterValue})
	err = result.Err()
	if errors.Is(err, mongo.ErrNoDocuments) {
		return deviceGroup, false, nil
	}
	if err != nil {
		return
	}
	err = result.Decode(&deviceGroup)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return deviceGroup, false, nil
	}
	return deviceGroup, true, err
}

func (this *Mongo) ListDeviceGroups(ctx context.Context, listOptions model.DeviceGroupListOptions) (result []models.DeviceGroup, total int64, err error) {
	opt := options.Find()
	opt.SetLimit(listOptions.Limit)
	opt.SetSkip(listOptions.Offset)

	parts := strings.Split(listOptions.SortBy, ".")
	sortby := DeviceGroupBson.Id
	switch parts[0] {
	case "id":
		sortby = DeviceGroupBson.Id
	case "name":
		sortby = DeviceGroupBson.Name
	default:
		sortby = DeviceGroupBson.Id
	}
	direction := int32(1)
	if len(parts) > 1 && parts[1] == "desc" {
		direction = int32(-1)
	}
	opt.SetSort(bson.D{{sortby, direction}})

	filter := bson.M{}
	if listOptions.Ids != nil {
		filter[DeviceGroupBson.Id] = bson.M{"$in": listOptions.Ids}
	}

	filterAnd := []interface{}{bson.M{NotDeletedFilterKey: NotDeletedFilterValue}}
	if listOptions.IgnoreGenerated {
		filterAnd = append(filterAnd, bson.M{"$or": []bson.M{
			{DeviceGroupBson.AutoGeneratedByDevice: bson.M{"$exists": false}},
			{DeviceGroupBson.AutoGeneratedByDevice: bson.M{"$eq": ""}},
		}})
	}

	search := strings.TrimSpace(listOptions.Search)
	if search != "" {
		escapedSearch := regexp.QuoteMeta(search)
		filter[DeviceGroupBson.Name] = bson.M{"$regex": escapedSearch, "$options": "i"}
	}

	if listOptions.AttributeKeys != nil {
		filter[DeviceGroupBson.Attributes[0].Key] = bson.M{"$in": listOptions.AttributeKeys}
	}
	if listOptions.AttributeValues != nil {
		filter[DeviceGroupBson.Attributes[0].Value] = bson.M{"$in": listOptions.AttributeValues}
	}
	if listOptions.DeviceIds != nil {
		filter[DeviceGroupBson.DeviceIds[0]] = bson.M{"$in": listOptions.DeviceIds}
	}

	if listOptions.Criteria != nil {
		if len(listOptions.Criteria) == 0 && this.config.PreventEmptyCriteriaListsAllBehavior {
			return []models.DeviceGroup{}, 0, nil
		}
		criteriaFilter := []interface{}{}
		for _, c := range listOptions.Criteria {
			if c.Interaction == "" {
				criteriaFilter = append(criteriaFilter, bson.M{"$or": []bson.M{
					{deviceGroupCriteriaShortKey: models.DeviceGroupFilterCriteria{
						Interaction:   models.REQUEST,
						FunctionId:    c.FunctionId,
						AspectId:      c.AspectId,
						DeviceClassId: c.DeviceClassId,
					}.Short()},
					{deviceGroupCriteriaShortKey: models.DeviceGroupFilterCriteria{
						Interaction:   models.EVENT,
						FunctionId:    c.FunctionId,
						AspectId:      c.AspectId,
						DeviceClassId: c.DeviceClassId,
					}.Short()},
					{deviceGroupCriteriaShortKey: models.DeviceGroupFilterCriteria{
						FunctionId:    c.FunctionId,
						AspectId:      c.AspectId,
						DeviceClassId: c.DeviceClassId,
					}.Short()},
				}})
			} else if c.Interaction == models.EVENT_AND_REQUEST {
				criteriaFilter = append(criteriaFilter, bson.M{deviceGroupCriteriaShortKey: models.DeviceGroupFilterCriteria{
					Interaction:   models.REQUEST,
					FunctionId:    c.FunctionId,
					AspectId:      c.AspectId,
					DeviceClassId: c.DeviceClassId,
				}.Short()})
				criteriaFilter = append(criteriaFilter, bson.M{deviceGroupCriteriaShortKey: models.DeviceGroupFilterCriteria{
					Interaction:   models.EVENT,
					FunctionId:    c.FunctionId,
					AspectId:      c.AspectId,
					DeviceClassId: c.DeviceClassId,
				}.Short()})
			} else {
				criteriaFilter = append(criteriaFilter, bson.M{deviceGroupCriteriaShortKey: models.DeviceGroupFilterCriteria{
					Interaction:   c.Interaction,
					FunctionId:    c.FunctionId,
					AspectId:      c.AspectId,
					DeviceClassId: c.DeviceClassId,
				}.Short()})
			}
		}
		if len(criteriaFilter) > 0 {
			filterAnd = append(filterAnd, criteriaFilter...)
		}
	}
	filter["$and"] = filterAnd

	cursor, err := this.deviceGroupCollection().Find(ctx, filter, opt)
	if err != nil {
		return nil, 0, err
	}
	err = cursor.All(ctx, &result)
	if err != nil {
		return nil, 0, err
	}
	total, err = this.deviceGroupCollection().CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, err
	}
	return result, total, nil
}

type DeviceGroupWithSyncInfo struct {
	models.DeviceGroup `bson:",inline"`
	SyncInfo           `bson:",inline"`
	SyncUser           string `bson:"sync_user"`
}

func (this *Mongo) GetDeviceGroupSyncUser(ctx context.Context, deviceGroupId string) (syncUser string, exists bool, err error) {
	result := this.deviceGroupCollection().FindOne(ctx, bson.M{DeviceGroupBson.Id: deviceGroupId})
	err = result.Err()
	if errors.Is(err, mongo.ErrNoDocuments) {
		return "", false, nil
	}
	if err != nil {
		return
	}
	deviceGroup := DeviceGroupWithSyncInfo{}
	err = result.Decode(&deviceGroup)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return syncUser, false, nil
	}
	syncUser = deviceGroup.SyncUser
	return syncUser, true, err
}

func (this *Mongo) SetDeviceGroup(ctx context.Context, deviceGroup models.DeviceGroup, syncHandler func(dg models.DeviceGroup, user string) error, user string) error {
	timestamp := time.Now().Unix()
	collection := this.deviceGroupCollection()
	_, err := this.deviceGroupCollection().ReplaceOne(ctx, bson.M{DeviceGroupBson.Id: deviceGroup.Id}, DeviceGroupWithSyncInfo{
		DeviceGroup: deviceGroup,
		SyncUser:    user,
		SyncInfo: SyncInfo{
			SyncTodo:          true,
			SyncDelete:        false,
			SyncUnixTimestamp: timestamp,
		},
	}, options.Replace().SetUpsert(true))
	if err != nil {
		return err
	}
	err = syncHandler(deviceGroup, user)
	if err != nil {
		this.config.GetLogger().Warn(fmt.Sprintf("error in SetDeviceGroup::syncHandler %v, will be retried later\n", err))
		return nil
	}
	err = this.setSynced(ctx, collection, DeviceGroupBson.Id, deviceGroup.Id, timestamp)
	if err != nil {
		this.config.GetLogger().Warn(fmt.Sprintf("error in SetDeviceGroup::setSynced %v, will be retried later\n", err))
		return nil
	}
	return nil
}

func (this *Mongo) RemoveDeviceGroup(ctx context.Context, id string, syncDeleteHandler func(models.DeviceGroup) error) error {
	old, exists, err := this.GetDeviceGroup(ctx, id)
	if err != nil {
		return err
	}
	if !exists {
		return nil
	}
	collection := this.deviceGroupCollection()
	err = this.setDeleted(ctx, collection, DeviceGroupBson.Id, id)
	if err != nil {
		return err
	}
	err = syncDeleteHandler(old)
	if err != nil {
		this.config.GetLogger().Warn(fmt.Sprintf("error in RemoveDeviceGroup::syncDeleteHandler %v, will be retried later\n", err))
		return nil
	}
	_, err = collection.DeleteOne(ctx, bson.M{DeviceGroupBson.Id: id})
	if err != nil {
		this.config.GetLogger().Warn(fmt.Sprintf("error in RemoveDeviceGroup::DeleteOne %v, will be retried later\n", err))
		return nil
	}
	return nil
}

func (this *Mongo) RetryDeviceGroupSync(lockduration time.Duration, syncDeleteHandler func(models.DeviceGroup) error, syncHandler func(dg models.DeviceGroup, user string) error) error {
	collection := this.deviceGroupCollection()
	jobs, err := FetchSyncJobs[DeviceGroupWithSyncInfo](collection, lockduration, FetchSyncJobsDefaultBatchSize)
	if err != nil {
		return err
	}
	for _, job := range jobs {
		if job.SyncDelete {
			err = syncDeleteHandler(job.DeviceGroup)
			if err != nil {
				this.config.GetLogger().Warn(fmt.Sprintf("error in RetryDeviceGroupSync::syncDeleteHandler %v, will be retried later\n", err))
				continue
			}
			ctx, _ := getTimeoutContext()
			_, err = collection.DeleteOne(ctx, bson.M{DeviceGroupBson.Id: job.Id})
			if err != nil {
				this.config.GetLogger().Warn(fmt.Sprintf("error in RetryDeviceGroupSync::DeleteOne %v, will be retried later\n", err))
				continue
			}
		} else if job.SyncTodo {
			err = syncHandler(job.DeviceGroup, job.SyncUser)
			if err != nil {
				this.config.GetLogger().Warn(fmt.Sprintf("error in RetryDeviceGroupSync::syncHandler %v, will be retried later\n", err))
				continue
			}
			ctx, _ := getTimeoutContext()
			err = this.setSynced(ctx, collection, DeviceGroupBson.Id, job.Id, job.SyncUnixTimestamp)
			if err != nil {
				this.config.GetLogger().Warn(fmt.Sprintf("error in RetryDeviceGroupSync::setSynced %v, will be retried later\n", err))
				continue
			}
		}
	}
	return nil
}
